AWSTemplateFormatVersion: '2010-09-09'
Description: 'Production-grade VPC | Mumbai | Free Tier | Multi-AZ'

Resources:
  DarkVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: dark-vpc
